# Tell Spring where to get the data from
spring:
  datasource:
    #url: jdbc:h2:mem:moviesdb       # name of your db - if you want to persist data between runs you can specify a file path: jdbc:h2:file:[path]
    #username: sa                    # default username is "sa"
    #password:                       # optional for h2
    #driverClassName: org.h2.Driver  # jdbc uses this to connect to database

    url: jdbc:postgresql://localhost:5432/warehouses?stringtype=unspecified
    username: postgres
    password:

  # now we need to tell jdbc what kind of database we're using
  #jpa:
    #database-platform: org.hibernate.dialect.H2Dialect        # tells spring data jpa that we're using h2 database
    #defer-datasource-initialization: true                     # tells JPA to wait until hibernate has initialized before loading the data to h2

server:
  port: 8282     # changes port number for server

# sets your logging level - default INFO
logging:
  level:
      com:
        skillstorm: debug

